language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=26
  - ANDROID_BUILD_TOOLS_VERSION=26.0.2
android:
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-26
before_script:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x "./source/gradlew"
script:
- "./source/gradlew build check"
before_install:
- openssl aes-256-cbc -K $encrypted_53560a4f2f5c_key -iv $encrypted_53560a4f2f5c_iv
  -in keystore.jks.enc -out keystore.jks -d
deploy:
  provider: releases
  api_key:
    secure: GIY/U09PVXi8B4FF5UEDFndh5ykNmq1LOfhw6wwrOqc7ZKropf8RlT3J5dKVY0gSiQCKmPpmq/A7aZGVs4x4Jn1SHrLNbY9LNsp79on9rbJK5WF4dTEsUhdHFCFUIwvEwBka2QFje7f4cxuBjOyJOHK+Fm33drYuK4gHo7zWbgpyi4I9DMjKlqNUCjnixV0ZZ10zBlBo+9GzYZLCGsFrqt8fkg7pYgdADAqk5UoNTClVk078U0CVyHedb77HW7vepj6cht5ypBiiK9cNZF2UtoQUppYM4qBqKhaQhJRzkTmRwyf0UNlBkgylKLOP+6r0a0ra/DoYzVLoD5CnYVERZPg3jPiT8Yol86whgr/d5vs8NTyOPNeBUq5Q9JKcAliy8W4Re7KRzsW00ssztKoy/p8gVzcGLFqGYArqXWAvVcPFrCMIrAEj3jFp2/j5AclCDCdw09mz+qCWj6Mw8U5Ya4SX4ENNWYVmR+WJGX2QLL5tObIF34cF/bo2fNGpBk21x6f3b7sCKtU2aMBKNA7IKcB+skhkXYsyD0TFb4O2/E41Yz1RdZF/nxYWwFp2S+RytTs6DvEXWduSY3sHDVRWBFKGiZ5BGeT5EhywlDs4RjXmMWhgvybKW3cbMuMq84tx5ud8pg1IAIfpLQCXMYOxYZWDYGa0epmHcqqtgmbwdOQ=
  file: app/build/outputs/apk/release/app-release.apk
  on:
    repo: namlxuit056/OrderFoodApp
    tags: true
