

language: android

android:
  components:
  - build-tools-26
  - android-26

  - extra-google-m2repository
  - extra-android-m2repository
   - tools
  - platform-tools


before_install:
 - chmod +x gradlew
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script:
  - ./gradlew test

